# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91a1184bb10e59deba80efac4287d0a6dd402afc49aa6cacd76bf31f49d7b2b61bf9cc29edc6bb1424325abeb3c888f4b64d6d004d319c6dd5ecf94d9ce08429

test:
  secret_key_base: 0fa25a3d8f5d5b696af3449c9140060cfcdf49cfdc5269e9c94762db6e5c9cc9bce7fefeb9758178b8c841bb40abe80260e45e1b6bcbc6ebc3c8d030f8193687

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
